<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>

<!DOCTYPE LISTA_MATRICULA [
  <!ELEMENT MATRICULA (NUMERO, DESC_TERRENO, NUM_AVERBACAO)>
  <!ELEMENT NUMERO (#PCDATA)>
  <!ELEMENT DESC_TERRENO (#PCDATA)>
  <!ELEMENT NUM_AVERBACAO (#PCDATA)>
]>



<LISTA_MATRICULA>

<inicio>
  Lista de Matriculas
</inicio>

<headers>
  <header>Numero</header>
  <header>Descricao do Terreno</header>
  <header>Numero Averbacoes</header>
</headers>

 <MATRICULA>
  <NUMERO>7465032</NUMERO>

<DESC_TERRENO>0702</DESC_TERRENO>
  <NUM_AVERBACAO>73549</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>7465032</NUMERO>

<DESC_TERRENO>0702</DESC_TERRENO>
  <NUM_AVERBACAO>39021</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>2138771</NUMERO>

<DESC_TERRENO>0768</DESC_TERRENO>
  <NUM_AVERBACAO>29877</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>2138771</NUMERO>

<DESC_TERRENO>0768</DESC_TERRENO>
  <NUM_AVERBACAO>85451</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>3747461</NUMERO>

<DESC_TERRENO>0219</DESC_TERRENO>
  <NUM_AVERBACAO>56043</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>3747461</NUMERO>

<DESC_TERRENO>0219</DESC_TERRENO>
  <NUM_AVERBACAO>86410</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>2911902</NUMERO>

<DESC_TERRENO>0336</DESC_TERRENO>
  <NUM_AVERBACAO>5434</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>2911902</NUMERO>

<DESC_TERRENO>0336</DESC_TERRENO>
  <NUM_AVERBACAO>33402</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>7069903</NUMERO>

<DESC_TERRENO>0958</DESC_TERRENO>
  <NUM_AVERBACAO>67887</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>7069903</NUMERO>

<DESC_TERRENO>0958</DESC_TERRENO>
  <NUM_AVERBACAO>95047</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>7264922</NUMERO>

<DESC_TERRENO>0660</DESC_TERRENO>
  <NUM_AVERBACAO>20286</NUM_AVERBACAO>

</MATRICULA>
 <MATRICULA>
  <NUMERO>7991295</NUMERO>

<DESC_TERRENO>0126</DESC_TERRENO>
  <NUM_AVERBACAO>20404</NUM_AVERBACAO>

</MATRICULA>
</LISTA_MATRICULA>
